### PR TITLE
Fix specs to be compliant with taxon/taxonomy factories improvements on solidus

### LINKED ISSUE #331: Test failures in `solidus_starter_frontend` after merging "Improve Taxon Validations and Factory" in Solidus
We have encountered test failures in the `solidus_starter_frontend` repository after merging [Improve Taxon validations and factory #4851](https://github.com/solidusio/solidus/pull/4851) in the main solidus repository.

As a result of these changes, the tests in the `solidus_starter_frontend` repository, with the main solidus branch, fail.
We need to investigate and resolve these test failures.

The failing tests can be seen here:
- [CircleCI pipeline for solidus_starter_frontend main](https://app.circleci.com/pipelines/github/solidusio/solidus_starter_frontend/1993/workflows/7f421ac1-a2be-4619-b3d4-633b30e44f26)

Special thanks to @kennyadsl for identifying this issue.

### PR DESCRIPTION
**Pull request by rainerdema**
## Summary

This PR addresses an issue that caused some specs on `solidus_starter_frontend` to fail.
The issue was identified to be related to recent changes made in the main Solidus repository (See the attached issue for more details)

We have updated the taxon specs to ensure compatibility with the latest changes.

Fixes #331

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Review by kennyadsl — APPROVED** [review]
Thanks for jumping on this, @rainerdema!

File: templates/spec/helpers/taxons_helper_spec.rb [hunk 1]
```diff
@@ -4,11 +4,10 @@
 
 RSpec.describe TaxonsHelper, type: :helper do
   describe '#taxon_seo_url' do
-    let(:taxon_permalink) { 'ruby-on-rails' }
-    let(:taxon) { create(:taxon, permalink: taxon_permalink) }
+    let(:taxon) { create(:taxon) }
 
     it 'is the nested taxons path for the taxon' do
-      expect(taxon_seo_url(taxon)).to eq("/t/#{taxon_permalink}")
+      expect(taxon_seo_url(taxon)).to eq("/t/#{taxon.permalink}")
```
Comment (elia) [inline templates/spec/helpers/taxons_helper_spec.rb:10]: Is this just a refactoring or there was something wrong with the original version?

I'm concerned that if the permalink is blank it will pass, but for the wrong reason

**Review by elia — APPROVED** [review]
👍 

Just left a question

**Review by waiting-for-dev — APPROVED** [review]
Thanks, @rainerdema. I'm also interested in Elia's question.

File: templates/spec/helpers/taxons_helper_spec.rb (hunk 1 above)
Comment (rainerdema) [reply templates/spec/helpers/taxons_helper_spec.rb]: I agree 👍 I also had doubts about this part.
The previous method of assigning a permalink to the taxon did not accurately reflect the current logic for generating taxon permalinks, which always includes a taxonomy now:
As a result, the default URL structure was incorrect and should have been something like `"brand-1/ruby-on-rails"` instead of just `"ruby-on-rails"`.

I have recreated the taxonomy and taxon using more appropriate names.
Please let me know if you have any feedback (or if we prefer to simply verify that the `taxon_seo_url` function returns the same value assigned to `taxon.permalink).

**Review by elia — APPROVED** [review]
