### PR TITLE
Fix clicking on autocomplete results

### LINKED ISSUE #313: Autocomplete search result does not respond to mouse click
## Solidus Version:

3.4.0.dev

## To Reproduce

1. It seems we currently can't run this repo's sandbox app because of https://github.com/solidusio/solidus/pull/4933. So, to run the sandbox app, you might need to checkout out the `gsmendoza/4932-fix-sandbox-error branch` from https://github.com/nebulab/solidus and run `bin/rails server` from there. 
2. Go to https://localhost:3000 and enter a search term in the search field.
3. Try clicking on a search result.

See this video:

https://user-images.githubusercontent.com/61476/217981582-fb687e86-0792-485f-8fa1-141130e766b1.mp4

## Current behavior

Nothing happens. However, I can select a search result by hitting `enter` with the keyboard.

## Expected behavior

I should be able to able to select a search result by clicking on the result.

## Desktop (please complete the following information):
 - OS:  Pop! OS 22.04 LTS
 - Browser: Google Chrome 
 - Version: 110.0.5481.77 (Official Build) (64-bit)

## Additional context

The autocomplete feature was introduced in https://github.com/solidusio/solidus_starter_frontend/pull/300.

### PR DESCRIPTION
**Pull request by kennyadsl**
## Description

Fixes #313

Follow-up for #300 

## Motivation and Context

By clicking on one of the results item, the `focusout` event is triggered and it acts before the `click` event is triggered, removing the list.

To solve this, we listen to all click events and do nothing if the click is internal to the autcomplete, otherwise it resets it.

## How Has This Been Tested?

By automated tests and in the sandbox locally

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by elia — APPROVED** [review]

**Review by gsmendoza — APPROVED** [review]

**Comment by gsmendoza** [comment]
Thanks @kennyadsl . I've confirmed that it's working :)

**Review by waiting-for-dev — APPROVED** [review]

File: templates/spec/system/search_spec.rb [hunk 1]
```diff
@@ -39,6 +39,15 @@
       expect(page.all('[data-search-target="result"]')[0][:class]).to include('autocomplete-results__item--current')
     end
 
+    it 'allows mouse click on results' do
+      fill_in 'keywords', with: 'ruby'
+      # wait for the autocomplete to show up
+      expect(page.all('[data-search-target="result"]')[0][:class]).to include('autocomplete-results__item--current')
```
Comment (waiting-for-dev) [inline templates/spec/system/search_spec.rb:45]: Are you sure that the `include` RSpec matcher will [wait](https://github.com/teamcapybara/capybara#asynchronous-javascript-ajax-and-friends) until the item is present?

**Review by waiting-for-dev — COMMENTED** [review]
Thanks, @kennyadsl. I left a question as I'm not sure the new test could become a flaky candidate.

File: templates/spec/system/search_spec.rb (hunk 1 above)
Comment (kennyadsl) [reply templates/spec/system/search_spec.rb:45]: I think it's more `page.all` that is waiting here, from the [`#all` doc](https://rubydoc.info/github/jnicklas/capybara/master/Capybara%2FNode%2FFinders:all):

> By default Capybara's waiting behavior will wait up to [default_max_wait_time](https://rubydoc.info/github/jnicklas/capybara/master/Capybara#configure-class_method) seconds for matching elements to be available and then return an empty result if none are available.

So, you are right that this is not ideal, meaning that we would probably have the same effect without the `include('autocomplete-results__item--current')` part. 

Because this is used in multiple tests over this file, if that's ok for you I'd merge this and shoot another PR that cleans this up in the whole file.

Comment (waiting-for-dev) [reply templates/spec/system/search_spec.rb:45]: Makes sense 👍
